module.exports = {
  yummlyAppId: "",
  yummlyAppKey: "",
  zomatoKey: "",
  edamamAppId: "",
  edamamAppKey: "",
  food2ForkKey: "",
  omdbApiKey: "",
  movieDbApiKey: "",
  tvDbApiKey: "",
  tvMazeApiKey: "",
  goodReadsApiKey: "",
  darkSkyApiKey: "",
  openUVApiKey: "",
  stormGlassApiKey: "",
  openWeatherMapKey: "",
  weatherbitApiKey: "",
  marvelPublicApiKey: "",
  marvelPrivateApiKey: "",
  airVisualApiKey: "",
  igdbApiKey: "",
  giantbombApiKey: "",
  comicVineApiKey: "",
  stackexchangeApiKey: "",
  cricApiKey: "",
  jcdecauxApiKey: "",
  footballOrgApikey: ""
}
